name: Update PokéAPI Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  build-and-push-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Check out the repository and fetch all branch history
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Configure Git and switch to the data branch
      - name: Switch to Data Branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout data

      # 5. Run all the parsers
      - name: Run Parsers
        run: python main.py --all

      # 6. Commit and push the new data
      - name: Commit and Push Data
        run: |
          echo "Restructuring data folders..."
          mv data/* .
          rm -r data

          git add .

          if git diff --staged --quiet; then
            echo "No data changes to commit."
          else
            git commit -m "Data update: $(date -u)"
            git push origin data
            echo "Data pushed successfully."
          fi
