name: Update PokéAPI Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  build-and-push-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Check out the 'main' branch to get the scripts
      - name: Check out main branch
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Run all the parsers (this creates the local 'data' folder)
      - name: Run Parsers
        run: python main.py --all

      # 5. Commit and push the data to the 'data' branch
      - name: Commit and Push Data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "Switching to the data branch..."
          git checkout -t origin/data

          echo "Restructuring data folders..."
          mv data/* .
          rm -r data

          git add .

          if git diff --staged --quiet; then
            echo "No data changes to commit."
          else
            git commit -m "Data update: $(date -u)"
            git push origin data
            echo "Data pushed successfully."
          fi
