name: Update PokéAPI Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  build-and-push-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out main branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Parsers
        run: python main.py --all

      - name: Commit and Push Data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git checkout --orphan data
          git rm -rf --cached .
          git add -f data/

          if git diff --staged --quiet; then
            echo "No data changes to commit."
          else
            git commit -m "Data update: $(date -u)"
            git push -f origin data
            echo "Data pushed successfully."
          fi
