name: Update PokéAPI Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-and-push-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Check out the repository and fetch all branch history
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Run all the parsers (this creates the local 'output' folder)
      - name: Run Parsers
        run: python main.py --all

      # 5. Switch to the data branch, clean old data, and commit new results
      - name: Commit and Push Data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout data

          new_gen_dir=$(find output -mindepth 1 -maxdepth 1 -type d -printf "%f\n" | head -n 1)

          if [ -z "$new_gen_dir" ]; then
            echo "No generation directory found in output. Nothing to commit."
            exit 0
          fi

          echo "Cleaning up old data directory: $new_gen_dir"
          rm -rf "$new_gen_dir"

          echo "Restructuring data folders..."
          mv -T output/$new_gen_dir .
          rm -r output

          git add .

          if git diff --staged --quiet; then
            echo "No data changes to commit."
          else
            git commit -m "Data update: $(date -u)"
            git push origin data
            echo "Data pushed successfully."
          fi
